Merge pull request #1 from thewebarea/HomeWork-3
thewebarea/kos-app pull request #2
Opened 2021-01-31 15:25 UTC by thewebarea

HOME WORK 3

2021-01-31 18:29 UTC, ZarMarathon requested changes
Где домашка?

2021-01-31 19:11 UTC, thewebarea commented
я вже нічого не розумію, я зробив вітку, її загнав сюди, ніби все ок в мене функціонал цього разу +- ворк, що чогось не видно чи що?

2021-01-31 19:13 UTC, thewebarea commented
https://github.com/thewebarea/kos-app/tree/HomeWork-3

2021-01-31 20:02 UTC, ZarMarathon commented
Ты пушил все свои изменения в созданную ветку? Есть только данные по второй домашке, по третьей - нет

2021-02-01 09:58 UTC, thewebarea commented
дійсно провтикав запушити.

2021-09-21 22:00 UTC, merged